# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#     * Rearrange models' order
#     * Make sure each model has one field with primary_key=True
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.
from __future__ import unicode_literals

from django.db import models

class Nivel1(models.Model):
    caracteristica = models.TextField(blank=True)
    promedio = models.FloatField(null=True, blank=True)
    class Meta:
        db_table = 'nivel1'

class Nivel2(models.Model):
    caracteristica = models.TextField(blank=True)
    genotipo = models.TextField(blank=True)
    promedio = models.FloatField(null=True, blank=True)
    class Meta:
        db_table = 'nivel2'

class Nivel3(models.Model):
    caracteristica = models.TextField(blank=True)
    genotipo = models.TextField(blank=True)
    tipo_paciente = models.TextField(blank=True)
    promedio = models.FloatField(null=True, blank=True)
    class Meta:
        db_table = 'nivel3'

class Nivel4(models.Model):
    caracteristica = models.TextField(blank=True)
    genotipo = models.TextField(blank=True)
    tipo_paciente = models.TextField(blank=True)
    grupo_etario = models.TextField(blank=True)
    promedio = models.FloatField(null=True, blank=True)
    class Meta:
        db_table = 'nivel4'

class Tbl1(models.Model):
    id = models.IntegerField(null=True, blank=True)
    institucion = models.TextField(blank=True)
    nombre = models.TextField(blank=True)
    especialidad = models.TextField(blank=True)
    hospital = models.TextField(blank=True)
    casos_20_39 = models.FloatField(null=True, blank=True)
    casos_40_59 = models.FloatField(null=True, blank=True)
    casos_60_69 = models.FloatField(null=True, blank=True)
    casos_70 = models.FloatField(null=True, blank=True)
    val_edad = models.FloatField(null=True, blank=True)
    casos_h = models.FloatField(null=True, blank=True)
    casos_m = models.FloatField(null=True, blank=True)
    val_genero = models.FloatField(null=True, blank=True)
    casos_naive = models.FloatField(null=True, blank=True)
    casos_retratados = models.FloatField(null=True, blank=True)
    val_tratamiento = models.FloatField(null=True, blank=True)
    casos_coinf_mono = models.FloatField(null=True, blank=True)
    casos_coinf_vih = models.FloatField(null=True, blank=True)
    casos_coinf_otra = models.FloatField(null=True, blank=True)
    val_coinf = models.FloatField(null=True, blank=True)
    casos_gen1a = models.FloatField(null=True, blank=True)
    casos_gen1b = models.FloatField(null=True, blank=True)
    casos_gen2 = models.FloatField(null=True, blank=True)
    casos_gen3 = models.FloatField(null=True, blank=True)
    casos_gen4 = models.FloatField(null=True, blank=True)
    casos_gen5 = models.FloatField(null=True, blank=True)
    casos_gen6 = models.FloatField(null=True, blank=True)
    val_geno = models.FloatField(null=True, blank=True)
    class Meta:
        db_table = 'tbl1'

class Tbl2(models.Model):
    id = models.IntegerField(null=True, blank=True)
    institucion = models.TextField(blank=True)
    nombre = models.TextField(blank=True)
    especialidad = models.TextField(blank=True)
    hospital = models.TextField(blank=True)
    casos_h_20_39 = models.FloatField(null=True, blank=True)
    casos_h_40_59 = models.FloatField(null=True, blank=True)
    casos_h_60_69 = models.FloatField(null=True, blank=True)
    casos_h_70 = models.FloatField(null=True, blank=True)
    val_hombre_edad = models.FloatField(null=True, blank=True)
    casos_m_20_39 = models.FloatField(null=True, blank=True)
    casos_m_40_59 = models.FloatField(null=True, blank=True)
    casos_m_60_69 = models.FloatField(null=True, blank=True)
    casos_m_70 = models.FloatField(null=True, blank=True)
    val_mujer_edad = models.FloatField(null=True, blank=True)
    casos_naive_mono = models.FloatField(null=True, blank=True)
    casos_naive_vih = models.FloatField(null=True, blank=True)
    casos_naive_otra = models.FloatField(null=True, blank=True)
    casos_naive_coinf = models.FloatField(null=True, blank=True)
    casos_retratados_mono = models.FloatField(null=True, blank=True)
    casos_retratados_vih = models.FloatField(null=True, blank=True)
    casos_retratados_otra = models.FloatField(null=True, blank=True)
    casos_retratados_coinf = models.FloatField(null=True, blank=True)
    casos_geno1a_mono = models.FloatField(null=True, blank=True)
    casos_geno1a_vih = models.FloatField(null=True, blank=True)
    casos_geno1a_otra = models.FloatField(null=True, blank=True)
    val_gen1a_coinf = models.FloatField(null=True, blank=True)
    casos_geno1b_mono = models.FloatField(null=True, blank=True)
    casos_geno1b_vih = models.FloatField(null=True, blank=True)
    casos_geno1b_otra = models.FloatField(null=True, blank=True)
    val_gen1b_coinf = models.FloatField(null=True, blank=True)
    casos_geno2_mono = models.FloatField(null=True, blank=True)
    casos_geno2_vih = models.FloatField(null=True, blank=True)
    casos_geno2_otra = models.FloatField(null=True, blank=True)
    val_gen2_coinf = models.FloatField(null=True, blank=True)
    casos_geno3_mono = models.FloatField(null=True, blank=True)
    casos_geno3_vih = models.FloatField(null=True, blank=True)
    casos_geno3_otra = models.FloatField(null=True, blank=True)
    val_gen3_coinf = models.FloatField(null=True, blank=True)
    casos_geno4_mono = models.FloatField(null=True, blank=True)
    casos_geno4_vih = models.FloatField(null=True, blank=True)
    casos_geno4_otra = models.FloatField(null=True, blank=True)
    val_gen4_coinf = models.FloatField(null=True, blank=True)
    casos_geno5_mono = models.FloatField(null=True, blank=True)
    casos_geno5_vih = models.FloatField(null=True, blank=True)
    casos_geno5_otra = models.FloatField(null=True, blank=True)
    val_gen5_coinf = models.FloatField(null=True, blank=True)
    casos_geno6_mono = models.FloatField(null=True, blank=True)
    casos_geno6_vih = models.FloatField(null=True, blank=True)
    casos_geno6_otra = models.FloatField(null=True, blank=True)
    val_gen6_coinf = models.FloatField(null=True, blank=True)
    class Meta:
        db_table = 'tbl2'

class Tbl3(models.Model):
    id = models.IntegerField(null=True, blank=True)
    institucion = models.TextField(blank=True)
    nombre = models.TextField(blank=True)
    especialidad = models.TextField(blank=True)
    hospital = models.TextField(blank=True)
    casos_mono_gen1a = models.FloatField(null=True, blank=True)
    casos_mono_gen1b = models.FloatField(null=True, blank=True)
    casos_mono_gen2 = models.FloatField(null=True, blank=True)
    val_mono_geno = models.FloatField(null=True, blank=True)
    casos_mono_h_gen1a = models.FloatField(null=True, blank=True)
    casos_mono_h_gen1b = models.FloatField(null=True, blank=True)
    casos_mono_h_gen2 = models.FloatField(null=True, blank=True)
    val_mono_h_geno = models.FloatField(null=True, blank=True)
    casos_mono_m_gen1a = models.FloatField(null=True, blank=True)
    casos_mono_m_gen1b = models.FloatField(null=True, blank=True)
    casos_mono_m_gen2 = models.FloatField(null=True, blank=True)
    val_mono_m_geno = models.FloatField(null=True, blank=True)
    casos_vih_gen1a = models.FloatField(null=True, blank=True)
    casos_vih_gen1b = models.FloatField(null=True, blank=True)
    casos_vih_gen2 = models.FloatField(null=True, blank=True)
    val_vih_geno = models.FloatField(null=True, blank=True)
    casos_vih_h_gen1a = models.FloatField(null=True, blank=True)
    casos_vih_h_gen1b = models.FloatField(null=True, blank=True)
    casos_vih_h_gen2 = models.FloatField(null=True, blank=True)
    val_vih_h_geno = models.FloatField(null=True, blank=True)
    casos_vih_m_gen1a = models.FloatField(null=True, blank=True)
    casos_vih_m_gen1b = models.FloatField(null=True, blank=True)
    casos_vih_m_gen2 = models.FloatField(null=True, blank=True)
    val_vih_m_geno = models.FloatField(null=True, blank=True)
    casos_otra_gen1a = models.FloatField(null=True, blank=True)
    casos_otra_gen1b = models.FloatField(null=True, blank=True)
    casos_otra_gen2 = models.FloatField(null=True, blank=True)
    val_otra_geno = models.FloatField(null=True, blank=True)
    casos_otra_h_gen1a = models.FloatField(null=True, blank=True)
    casos_otra_h_gen1b = models.FloatField(null=True, blank=True)
    casos_otra_h_gen2 = models.FloatField(null=True, blank=True)
    val_otra_h_geno = models.FloatField(null=True, blank=True)
    casos_otra_m_gen1a = models.FloatField(null=True, blank=True)
    casos_otra_m_gen1b = models.FloatField(null=True, blank=True)
    casos_otra_m_gen2 = models.FloatField(null=True, blank=True)
    val_otra_m_geno = models.FloatField(null=True, blank=True)
    class Meta:
        db_table = 'tbl3'

class Tbl4(models.Model):
    id = models.IntegerField(null=True, blank=True)
    institucion = models.TextField(blank=True)
    nombre = models.TextField(blank=True)
    especialidad = models.TextField(blank=True)
    hospital = models.TextField(blank=True)
    casos_mono_20_39_gen1a = models.FloatField(null=True, blank=True)
    casos_mono_20_39_gen1b = models.FloatField(null=True, blank=True)
    casos_mono_20_39_gen2 = models.FloatField(null=True, blank=True)
    val_mono_20_39_geno = models.FloatField(null=True, blank=True)
    casos_mono_40_59_gen1a = models.FloatField(null=True, blank=True)
    casos_mono_40_59_gen1b = models.FloatField(null=True, blank=True)
    casos_mono_40_59_gen2 = models.FloatField(null=True, blank=True)
    val_mono_40_59_geno = models.FloatField(null=True, blank=True)
    casos_mono_60_69_gen1a = models.FloatField(null=True, blank=True)
    casos_mono_60_69_gen1b = models.FloatField(null=True, blank=True)
    casos_mono_60_69_gen2 = models.FloatField(null=True, blank=True)
    val_mono_60_69_geno = models.FloatField(null=True, blank=True)
    casos_mono_70_gen1a = models.FloatField(null=True, blank=True)
    casos_mono_70_gen1b = models.FloatField(null=True, blank=True)
    casos_mono_70_gen2 = models.FloatField(null=True, blank=True)
    val_mono_70_geno = models.FloatField(null=True, blank=True)
    casos_vih_20_39_gen1a = models.FloatField(null=True, blank=True)
    casos_vih_20_39_gen1b = models.FloatField(null=True, blank=True)
    casos_vih_20_39_gen2 = models.FloatField(null=True, blank=True)
    val_vih_20_39_geno = models.FloatField(null=True, blank=True)
    casos_vih_40_59_gen1a = models.FloatField(null=True, blank=True)
    casos_vih_40_59_gen1b = models.FloatField(null=True, blank=True)
    casos_vih_40_59_gen2 = models.FloatField(null=True, blank=True)
    val_vih_40_59_geno = models.FloatField(null=True, blank=True)
    casos_vih_60_69_gen1a = models.FloatField(null=True, blank=True)
    casos_vih_60_69_gen1b = models.FloatField(null=True, blank=True)
    casos_vih_60_69_gen2 = models.FloatField(null=True, blank=True)
    val_vih_60_69_geno = models.FloatField(null=True, blank=True)
    casos_vih_70_gen1a = models.FloatField(null=True, blank=True)
    casos_vih_70_gen1b = models.FloatField(null=True, blank=True)
    casos_vih_70_gen2 = models.FloatField(null=True, blank=True)
    val_vih_70_geno = models.FloatField(null=True, blank=True)
    casos_otra_20_39_gen1a = models.FloatField(null=True, blank=True)
    casos_otra_20_39_gen1b = models.FloatField(null=True, blank=True)
    casos_otra_20_39_gen2 = models.FloatField(null=True, blank=True)
    val_otra_20_39_geno = models.FloatField(null=True, blank=True)
    casos_otra_40_59_gen1a = models.FloatField(null=True, blank=True)
    casos_otra_40_59_gen1b = models.FloatField(null=True, blank=True)
    casos_otra_40_59_gen2 = models.FloatField(null=True, blank=True)
    val_otra_40_59_geno = models.FloatField(null=True, blank=True)
    casos_otra_60_69_gen1a = models.FloatField(null=True, blank=True)
    casos_otra_60_69_gen1b = models.FloatField(null=True, blank=True)
    casos_otra_60_69_gen2 = models.FloatField(null=True, blank=True)
    val_otra_60_69_geno = models.FloatField(null=True, blank=True)
    casos_otra_70_gen1a = models.FloatField(null=True, blank=True)
    casos_otra_70_gen1b = models.FloatField(null=True, blank=True)
    casos_otra_70_gen2 = models.FloatField(null=True, blank=True)
    val_otra_70_geno = models.FloatField(null=True, blank=True)
    casos_mono_naive_gen1a = models.FloatField(null=True, blank=True)
    casos_mono_naive_gen1b = models.FloatField(null=True, blank=True)
    casos_mono_naive_gen2 = models.FloatField(null=True, blank=True)
    val_mono_naive_geno = models.FloatField(null=True, blank=True)
    casos_mono_retratados_gen1a = models.FloatField(null=True, blank=True)
    casos_mono_retratados_gen1b = models.FloatField(null=True, blank=True)
    casos_mono_retratados_gen2 = models.FloatField(null=True, blank=True)
    val_mono_retratados_geno = models.FloatField(null=True, blank=True)
    casos_vih_naive_gen1a = models.FloatField(null=True, blank=True)
    casos_vih_naive_gen1b = models.FloatField(null=True, blank=True)
    casos_vih_naive_gen2 = models.FloatField(null=True, blank=True)
    val_vih_naive_geno = models.FloatField(null=True, blank=True)
    casos_vih_retratados_gen1a = models.FloatField(null=True, blank=True)
    casos_vih_retratados_gen1b = models.FloatField(null=True, blank=True)
    casos_vih_retratados_gen2 = models.FloatField(null=True, blank=True)
    val_vih_retratados_geno = models.FloatField(null=True, blank=True)
    casos_otra_naive_gen1a = models.FloatField(null=True, blank=True)
    casos_otra_naive_gen1b = models.FloatField(null=True, blank=True)
    casos_otra_naive_gen2 = models.FloatField(null=True, blank=True)
    val_otra_naive_geno = models.FloatField(null=True, blank=True)
    casos_otra_retratados_gen1a = models.FloatField(null=True, blank=True)
    casos_otra_retratados_gen1b = models.FloatField(null=True, blank=True)
    casos_otra_retratados_gen2 = models.FloatField(null=True, blank=True)
    val_otra_retratados_geno = models.FloatField(null=True, blank=True)
    class Meta:
        db_table = 'tbl4'

class Tbl5(models.Model):
    id = models.IntegerField(null=True, blank=True)
    institucion = models.TextField(blank=True)
    nombre = models.TextField(blank=True)
    especialidad = models.TextField(blank=True)
    hospital = models.TextField(blank=True)
    mono_h_20_30_gen1a_naive = models.FloatField(null=True, blank=True)
    mono_h_20_30_gen1a_retratados = models.FloatField(null=True, blank=True)
    mono_h_20_30_gen1b_naive = models.FloatField(null=True, blank=True)
    mono_h_20_30_gen1b_retratados = models.FloatField(null=True, blank=True)
    mono_h_20_30_gen2_naive = models.FloatField(null=True, blank=True)
    mono_h_20_30_gen2_retratados = models.FloatField(null=True, blank=True)
    val_mono_h_20_30 = models.FloatField(null=True, blank=True)
    mono_h_40_69_gen1a_naive = models.FloatField(null=True, blank=True)
    mono_h_40_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    mono_h_40_69_gen1b_naive = models.FloatField(null=True, blank=True)
    mono_h_40_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    mono_h_40_69_gen2_naive = models.FloatField(null=True, blank=True)
    mono_h_40_69_gen2_retratados = models.FloatField(null=True, blank=True)
    val_mono_h_40_69 = models.FloatField(null=True, blank=True)
    mono_h_60_69_gen1a_naive = models.FloatField(null=True, blank=True)
    mono_h_60_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    mono_h_60_69_gen1b_naive = models.FloatField(null=True, blank=True)
    mono_h_60_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    mono_h_60_69_gen2_naive = models.FloatField(null=True, blank=True)
    mono_h_60_69_gen2_retratados = models.FloatField(null=True, blank=True)
    val_mono_h_60_69 = models.FloatField(null=True, blank=True)
    mono_h_70_gen1a_naive = models.FloatField(null=True, blank=True)
    mono_h_70_gen1a_retratados = models.FloatField(null=True, blank=True)
    mono_h_70_gen1b_naive = models.FloatField(null=True, blank=True)
    mono_h_70_gen1b_retratados = models.FloatField(null=True, blank=True)
    mono_h_70_gen2_naive = models.FloatField(null=True, blank=True)
    mono_h_70_gen2_retratados = models.FloatField(null=True, blank=True)
    val_mono_h_70 = models.FloatField(null=True, blank=True)
    mono_m_20_30_gen1a_naive = models.FloatField(null=True, blank=True)
    mono_m_20_30_gen1a_retratados = models.FloatField(null=True, blank=True)
    mono_m_20_30_gen1b_naive = models.FloatField(null=True, blank=True)
    mono_m_20_30_gen1b_retratados = models.FloatField(null=True, blank=True)
    mono_m_20_30_gen2_naive = models.FloatField(null=True, blank=True)
    mono_m_20_30_gen2_retratados = models.FloatField(null=True, blank=True)
    val_mono_m_20_30 = models.FloatField(null=True, blank=True)
    mono_m_40_69_gen1a_naive = models.FloatField(null=True, blank=True)
    mono_m_40_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    mono_m_40_69_gen1b_naive = models.FloatField(null=True, blank=True)
    mono_m_40_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    mono_m_40_69_gen2_naive = models.FloatField(null=True, blank=True)
    mono_m_40_69_gen2_retratados = models.FloatField(null=True, blank=True)
    val_mono_m_40_69 = models.FloatField(null=True, blank=True)
    mono_m_60_69_gen1a_naive = models.FloatField(null=True, blank=True)
    mono_m_60_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    mono_m_60_69_gen1b_naive = models.FloatField(null=True, blank=True)
    mono_m_60_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    mono_m_60_69_gen2_naive = models.FloatField(null=True, blank=True)
    mono_m_60_69_gen2_retratados = models.FloatField(null=True, blank=True)
    val_mono_m_60_69 = models.FloatField(null=True, blank=True)
    mono_m_70_gen1a_naive = models.FloatField(null=True, blank=True)
    mono_m_70_gen1a_retratados = models.FloatField(null=True, blank=True)
    mono_m_70_gen1b_naive = models.FloatField(null=True, blank=True)
    mono_m_70_gen1b_retratados = models.FloatField(null=True, blank=True)
    mono_m_70_gen2_naive = models.FloatField(null=True, blank=True)
    mono_m_70_gen2_retratados = models.FloatField(null=True, blank=True)
    val_mono_m_70 = models.FloatField(null=True, blank=True)
    vih_h_20_30_gen1a_naive = models.FloatField(null=True, blank=True)
    vih_h_20_30_gen1a_retratados = models.FloatField(null=True, blank=True)
    vih_h_20_30_gen1b_naive = models.FloatField(null=True, blank=True)
    vih_h_20_30_gen1b_retratados = models.FloatField(null=True, blank=True)
    vih_h_20_30_gen2_naive = models.FloatField(null=True, blank=True)
    vih_h_20_30_gen2_retratados = models.FloatField(null=True, blank=True)
    val_vih_h_20_30 = models.FloatField(null=True, blank=True)
    vih_h_40_69_gen1a_naive = models.FloatField(null=True, blank=True)
    vih_h_40_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    vih_h_40_69_gen1b_naive = models.FloatField(null=True, blank=True)
    vih_h_40_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    vih_h_40_69_gen2_naive = models.FloatField(null=True, blank=True)
    vih_h_40_69_gen2_retratados = models.FloatField(null=True, blank=True)
    val_vih_h_40_69 = models.FloatField(null=True, blank=True)
    vih_h_60_69_gen1a_naive = models.FloatField(null=True, blank=True)
    vih_h_60_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    vih_h_60_69_gen1b_naive = models.FloatField(null=True, blank=True)
    vih_h_60_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    vih_h_60_69_gen2_naive = models.FloatField(null=True, blank=True)
    vih_h_60_69_gen2_retratados = models.FloatField(null=True, blank=True)
    val_vih_h_60_69 = models.FloatField(null=True, blank=True)
    vih_h_70_gen1a_naive = models.FloatField(null=True, blank=True)
    vih_h_70_gen1a_retratados = models.FloatField(null=True, blank=True)
    vih_h_70_gen1b_naive = models.FloatField(null=True, blank=True)
    vih_h_70_gen1b_retratados = models.FloatField(null=True, blank=True)
    vih_h_70_gen2_naive = models.FloatField(null=True, blank=True)
    vih_h_70_gen2_retratados = models.FloatField(null=True, blank=True)
    val_vih_h_70 = models.FloatField(null=True, blank=True)
    vih_m_20_30_gen1a_naive = models.FloatField(null=True, blank=True)
    vih_m_20_30_gen1a_retratados = models.FloatField(null=True, blank=True)
    vih_m_20_30_gen1b_naive = models.FloatField(null=True, blank=True)
    vih_m_20_30_gen1b_retratados = models.FloatField(null=True, blank=True)
    vih_m_20_30_gen2_naive = models.FloatField(null=True, blank=True)
    vih_m_20_30_gen2_retratados = models.FloatField(null=True, blank=True)
    val_vih_m_20_30 = models.FloatField(null=True, blank=True)
    vih_m_40_69_gen1a_naive = models.FloatField(null=True, blank=True)
    vih_m_40_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    vih_m_40_69_gen1b_naive = models.FloatField(null=True, blank=True)
    vih_m_40_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    vih_m_40_69_gen2_naive = models.FloatField(null=True, blank=True)
    vih_m_40_69_gen2_retratados = models.FloatField(null=True, blank=True)
    val_vih_m_40_69 = models.FloatField(null=True, blank=True)
    vih_m_60_69_gen1a_naive = models.FloatField(null=True, blank=True)
    vih_m_60_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    vih_m_60_69_gen1b_naive = models.FloatField(null=True, blank=True)
    vih_m_60_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    vih_m_60_69_gen2_naive = models.FloatField(null=True, blank=True)
    vih_m_60_69_gen2_retratados = models.FloatField(null=True, blank=True)
    val_vih_m_60_69 = models.FloatField(null=True, blank=True)
    vih_m_70_gen1a_naive = models.FloatField(null=True, blank=True)
    vih_m_70_gen1a_retratados = models.FloatField(null=True, blank=True)
    vih_m_70_gen1b_naive = models.FloatField(null=True, blank=True)
    vih_m_70_gen1b_retratados = models.FloatField(null=True, blank=True)
    vih_m_70_gen2_naive = models.FloatField(null=True, blank=True)
    vih_m_70_gen2_retratados = models.FloatField(null=True, blank=True)
    val_vih_m_70 = models.FloatField(null=True, blank=True)
    otra_h_20_30_gen1a_naive = models.FloatField(null=True, blank=True)
    otra_h_20_30_gen1a_retratados = models.FloatField(null=True, blank=True)
    otra_h_20_30_gen1b_naive = models.FloatField(null=True, blank=True)
    otra_h_20_30_gen1b_retratados = models.FloatField(null=True, blank=True)
    otra_h_20_30_gen2_naive = models.FloatField(null=True, blank=True)
    otra_h_20_30_gen2_retratados = models.FloatField(null=True, blank=True)
    val_otra_h_20_30 = models.FloatField(null=True, blank=True)
    otra_h_40_69_gen1a_naive = models.FloatField(null=True, blank=True)
    otra_h_40_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    otra_h_40_69_gen1b_naive = models.FloatField(null=True, blank=True)
    otra_h_40_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    otra_h_40_69_gen2_naive = models.FloatField(null=True, blank=True)
    otra_h_40_69_gen2_retratados = models.FloatField(null=True, blank=True)
    val_otra_h_40_69 = models.FloatField(null=True, blank=True)
    otra_h_60_69_gen1a_naive = models.FloatField(null=True, blank=True)
    otra_h_60_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    otra_h_60_69_gen1b_naive = models.FloatField(null=True, blank=True)
    otra_h_60_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    otra_h_60_69_gen2_naive = models.FloatField(null=True, blank=True)
    otra_h_60_69_gen2_retratados = models.FloatField(null=True, blank=True)
    val_otra_h_60_69 = models.FloatField(null=True, blank=True)
    otra_h_70_gen1a_naive = models.FloatField(null=True, blank=True)
    otra_h_70_gen1a_retratados = models.FloatField(null=True, blank=True)
    otra_h_70_gen1b_naive = models.FloatField(null=True, blank=True)
    otra_h_70_gen1b_retratados = models.FloatField(null=True, blank=True)
    otra_h_70_gen2_naive = models.FloatField(null=True, blank=True)
    otra_h_70_gen2_retratados = models.FloatField(null=True, blank=True)
    val_otra_h_70 = models.FloatField(null=True, blank=True)
    otra_m_20_30_gen1a_naive = models.FloatField(null=True, blank=True)
    otra_m_20_30_gen1a_retratados = models.FloatField(null=True, blank=True)
    otra_m_20_30_gen1b_naive = models.FloatField(null=True, blank=True)
    otra_m_20_30_gen1b_retratados = models.FloatField(null=True, blank=True)
    otra_m_20_30_gen2_naive = models.FloatField(null=True, blank=True)
    otra_m_20_30_gen2_retratados = models.FloatField(null=True, blank=True)
    val_otra_m_20_30 = models.FloatField(null=True, blank=True)
    otra_m_40_69_gen1a_naive = models.FloatField(null=True, blank=True)
    otra_m_40_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    otra_m_40_69_gen1b_naive = models.FloatField(null=True, blank=True)
    otra_m_40_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    otra_m_40_69_gen2_naive = models.FloatField(null=True, blank=True)
    otra_m_40_69_gen2_retratados = models.FloatField(null=True, blank=True)
    val_otra_m_40_69 = models.FloatField(null=True, blank=True)
    otra_m_60_69_gen1a_naive = models.FloatField(null=True, blank=True)
    otra_m_60_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    otra_m_60_69_gen1b_naive = models.FloatField(null=True, blank=True)
    otra_m_60_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    otra_m_60_69_gen2_naive = models.FloatField(null=True, blank=True)
    otra_m_60_69_gen2_retratados = models.FloatField(null=True, blank=True)
    val_otra_m_60_69 = models.FloatField(null=True, blank=True)
    otra_m_70_gen1a_naive = models.FloatField(null=True, blank=True)
    otra_m_70_gen1a_retratados = models.FloatField(null=True, blank=True)
    otra_m_70_gen1b_naive = models.FloatField(null=True, blank=True)
    otra_m_70_gen1b_retratados = models.FloatField(null=True, blank=True)
    otra_m_70_gen2_naive = models.FloatField(null=True, blank=True)
    otra_m_70_gen2_retratados = models.FloatField(null=True, blank=True)
    val_otra_m_70 = models.FloatField(null=True, blank=True)
    class Meta:
        db_table = 'tbl5'

class Tbl6(models.Model):
    id = models.IntegerField(null=True, blank=True)
    institucion = models.TextField(blank=True)
    nombre = models.TextField(blank=True)
    especialidad = models.TextField(blank=True)
    hospital = models.TextField(blank=True)
    si_conoce_inh_prot = models.FloatField(null=True, blank=True)
    no_conoce_inh_prot = models.FloatField(null=True, blank=True)
    mono_h_20_39_gen1a_naive = models.FloatField(null=True, blank=True)
    mono_h_20_39_gen1a_retratados = models.FloatField(null=True, blank=True)
    mono_h_20_39_gen1b_naive = models.FloatField(null=True, blank=True)
    mono_h_20_39_gen1b_retratados = models.FloatField(null=True, blank=True)
    mono_h_20_39_gen2_naive = models.FloatField(null=True, blank=True)
    mono_h_20_39_gen2_retratados = models.FloatField(null=True, blank=True)
    mono_h_40_59_gen1a_naive = models.FloatField(null=True, blank=True)
    mono_h_40_59_gen1a_retratados = models.FloatField(null=True, blank=True)
    mono_h_40_59_gen1b_naive = models.FloatField(null=True, blank=True)
    mono_h_40_59_gen1b_retratados = models.FloatField(null=True, blank=True)
    mono_h_40_59_gen2_naive = models.FloatField(null=True, blank=True)
    mono_h_40_59_gen2_retratados = models.FloatField(null=True, blank=True)
    mono_h_60_69_gen1a_naive = models.FloatField(null=True, blank=True)
    mono_h_60_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    mono_h_60_69_gen1b_naive = models.FloatField(null=True, blank=True)
    mono_h_60_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    mono_h_60_69_gen2_naive = models.FloatField(null=True, blank=True)
    mono_h_60_69_gen2_retratados = models.FloatField(null=True, blank=True)
    mono_h_70_gen1a_naive = models.FloatField(null=True, blank=True)
    mono_h_70_gen1a_retratados = models.FloatField(null=True, blank=True)
    mono_h_70_gen1b_naive = models.FloatField(null=True, blank=True)
    mono_h_70_gen1b_retratados = models.FloatField(null=True, blank=True)
    mono_h_70_gen2_naive = models.FloatField(null=True, blank=True)
    mono_h_70_gen2_retratados = models.FloatField(null=True, blank=True)
    mono_m_20_39_gen1a_naive = models.FloatField(null=True, blank=True)
    mono_m_20_39_gen1a_retratados = models.FloatField(null=True, blank=True)
    mono_m_20_39_gen1b_naive = models.FloatField(null=True, blank=True)
    mono_m_20_39_gen1b_retratados = models.FloatField(null=True, blank=True)
    mono_m_20_39_gen2_naive = models.FloatField(null=True, blank=True)
    mono_m_20_39_gen2_retratados = models.FloatField(null=True, blank=True)
    mono_m_40_59_gen1a_naive = models.FloatField(null=True, blank=True)
    mono_m_40_59_gen1a_retratados = models.FloatField(null=True, blank=True)
    mono_m_40_59_gen1b_naive = models.FloatField(null=True, blank=True)
    mono_m_40_59_gen1b_retratados = models.FloatField(null=True, blank=True)
    mono_m_40_59_gen2_naive = models.FloatField(null=True, blank=True)
    mono_m_40_59_gen2_retratados = models.FloatField(null=True, blank=True)
    mono_m_60_69_gen1a_naive = models.FloatField(null=True, blank=True)
    mono_m_60_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    mono_m_60_69_gen1b_naive = models.FloatField(null=True, blank=True)
    mono_m_60_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    mono_m_60_69_gen2_naive = models.FloatField(null=True, blank=True)
    mono_m_60_69_gen2_retratados = models.FloatField(null=True, blank=True)
    mono_m_70_gen1a_naive = models.FloatField(null=True, blank=True)
    mono_m_70_gen1a_retratados = models.FloatField(null=True, blank=True)
    mono_m_70_gen1b_naive = models.FloatField(null=True, blank=True)
    mono_m_70_gen1b_retratados = models.FloatField(null=True, blank=True)
    mono_m_70_gen2_naive = models.FloatField(null=True, blank=True)
    mono_m_70_gen2_retratados = models.FloatField(null=True, blank=True)
    vih_h_20_39_gen1a_naive = models.FloatField(null=True, blank=True)
    vih_h_20_39_gen1a_retratados = models.FloatField(null=True, blank=True)
    vih_h_20_39_gen1b_naive = models.FloatField(null=True, blank=True)
    vih_h_20_39_gen1b_retratados = models.FloatField(null=True, blank=True)
    vih_h_20_39_gen2_naive = models.FloatField(null=True, blank=True)
    vih_h_20_39_gen2_retratados = models.FloatField(null=True, blank=True)
    vih_h_40_59_gen1a_naive = models.FloatField(null=True, blank=True)
    vih_h_40_59_gen1a_retratados = models.FloatField(null=True, blank=True)
    vih_h_40_59_gen1b_naive = models.FloatField(null=True, blank=True)
    vih_h_40_59_gen1b_retratados = models.FloatField(null=True, blank=True)
    vih_h_40_59_gen2_naive = models.FloatField(null=True, blank=True)
    vih_h_40_59_gen2_retratados = models.FloatField(null=True, blank=True)
    vih_h_60_69_gen1a_naive = models.FloatField(null=True, blank=True)
    vih_h_60_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    vih_h_60_69_gen1b_naive = models.FloatField(null=True, blank=True)
    vih_h_60_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    vih_h_60_69_gen2_naive = models.FloatField(null=True, blank=True)
    vih_h_60_69_gen2_retratados = models.FloatField(null=True, blank=True)
    vih_h_70_gen1a_naive = models.FloatField(null=True, blank=True)
    vih_h_70_gen1a_retratados = models.FloatField(null=True, blank=True)
    vih_h_70_gen1b_naive = models.FloatField(null=True, blank=True)
    vih_h_70_gen1b_retratados = models.FloatField(null=True, blank=True)
    vih_h_70_gen2_naive = models.FloatField(null=True, blank=True)
    vih_h_70_gen2_retratados = models.FloatField(null=True, blank=True)
    vih_m_20_39_gen1a_naive = models.FloatField(null=True, blank=True)
    vih_m_20_39_gen1a_retratados = models.FloatField(null=True, blank=True)
    vih_m_20_39_gen1b_naive = models.FloatField(null=True, blank=True)
    vih_m_20_39_gen1b_retratados = models.FloatField(null=True, blank=True)
    vih_m_20_39_gen2_naive = models.FloatField(null=True, blank=True)
    vih_m_20_39_gen2_retratados = models.FloatField(null=True, blank=True)
    vih_m_40_59_gen1a_naive = models.FloatField(null=True, blank=True)
    vih_m_40_59_gen1a_retratados = models.FloatField(null=True, blank=True)
    vih_m_40_59_gen1b_naive = models.FloatField(null=True, blank=True)
    vih_m_40_59_gen1b_retratados = models.FloatField(null=True, blank=True)
    vih_m_40_59_gen2_naive = models.FloatField(null=True, blank=True)
    vih_m_40_59_gen2_retratados = models.FloatField(null=True, blank=True)
    vih_m_60_69_gen1a_naive = models.FloatField(null=True, blank=True)
    vih_m_60_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    vih_m_60_69_gen1b_naive = models.FloatField(null=True, blank=True)
    vih_m_60_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    vih_m_60_69_gen2_naive = models.FloatField(null=True, blank=True)
    vih_m_60_69_gen2_retratados = models.FloatField(null=True, blank=True)
    vih_m_70_gen1a_naive = models.FloatField(null=True, blank=True)
    vih_m_70_gen1a_retratados = models.FloatField(null=True, blank=True)
    vih_m_70_gen1b_naive = models.FloatField(null=True, blank=True)
    vih_m_70_gen1b_retratados = models.FloatField(null=True, blank=True)
    vih_m_70_gen2_naive = models.FloatField(null=True, blank=True)
    vih_m_70_gen2_retratados = models.FloatField(null=True, blank=True)
    otra_h_20_39_gen1a_naive = models.FloatField(null=True, blank=True)
    otra_h_20_39_gen1a_retratados = models.FloatField(null=True, blank=True)
    otra_h_20_39_gen1b_naive = models.FloatField(null=True, blank=True)
    otra_h_20_39_gen1b_retratados = models.FloatField(null=True, blank=True)
    otra_h_20_39_gen2_naive = models.FloatField(null=True, blank=True)
    otra_h_20_39_gen2_retratados = models.FloatField(null=True, blank=True)
    otra_h_40_59_gen1a_naive = models.FloatField(null=True, blank=True)
    otra_h_40_59_gen1a_retratados = models.FloatField(null=True, blank=True)
    otra_h_40_59_gen1b_naive = models.FloatField(null=True, blank=True)
    otra_h_40_59_gen1b_retratados = models.FloatField(null=True, blank=True)
    otra_h_40_59_gen2_naive = models.FloatField(null=True, blank=True)
    otra_h_40_59_gen2_retratados = models.FloatField(null=True, blank=True)
    otra_h_60_69_gen1a_naive = models.FloatField(null=True, blank=True)
    otra_h_60_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    otra_h_60_69_gen1b_naive = models.FloatField(null=True, blank=True)
    otra_h_60_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    otra_h_60_69_gen2_naive = models.FloatField(null=True, blank=True)
    otra_h_60_69_gen2_retratados = models.FloatField(null=True, blank=True)
    otra_h_70_gen1a_naive = models.FloatField(null=True, blank=True)
    otra_h_70_gen1a_retratados = models.FloatField(null=True, blank=True)
    otra_h_70_gen1b_naive = models.FloatField(null=True, blank=True)
    otra_h_70_gen1b_retratados = models.FloatField(null=True, blank=True)
    otra_h_70_gen2_naive = models.FloatField(null=True, blank=True)
    otra_h_70_gen2_retratados = models.FloatField(null=True, blank=True)
    otra_m_20_39_gen1a_naive = models.FloatField(null=True, blank=True)
    otra_m_20_39_gen1a_retratados = models.FloatField(null=True, blank=True)
    otra_m_20_39_gen1b_naive = models.FloatField(null=True, blank=True)
    otra_m_20_39_gen1b_retratados = models.FloatField(null=True, blank=True)
    otra_m_20_39_gen2_naive = models.FloatField(null=True, blank=True)
    otra_m_20_39_gen2_retratados = models.FloatField(null=True, blank=True)
    otra_m_40_59_gen1a_naive = models.FloatField(null=True, blank=True)
    otra_m_40_59_gen1a_retratados = models.FloatField(null=True, blank=True)
    otra_m_40_59_gen1b_naive = models.FloatField(null=True, blank=True)
    otra_m_40_59_gen1b_retratados = models.FloatField(null=True, blank=True)
    otra_m_40_59_gen2_naive = models.FloatField(null=True, blank=True)
    otra_m_40_59_gen2_retratados = models.FloatField(null=True, blank=True)
    otra_m_60_69_gen1a_naive = models.FloatField(null=True, blank=True)
    otra_m_60_69_gen1a_retratados = models.FloatField(null=True, blank=True)
    otra_m_60_69_gen1b_naive = models.FloatField(null=True, blank=True)
    otra_m_60_69_gen1b_retratados = models.FloatField(null=True, blank=True)
    otra_m_60_69_gen2_naive = models.FloatField(null=True, blank=True)
    otra_m_60_69_gen2_retratados = models.FloatField(null=True, blank=True)
    otra_m_70_gen1a_naive = models.FloatField(null=True, blank=True)
    otra_m_70_gen1a_retratados = models.FloatField(null=True, blank=True)
    otra_m_70_gen1b_naive = models.FloatField(null=True, blank=True)
    otra_m_70_gen1b_retratados = models.FloatField(null=True, blank=True)
    otra_m_70_gen2_naive = models.FloatField(null=True, blank=True)
    otra_m_70_gen2_retratados = models.FloatField(null=True, blank=True)
    class Meta:
        db_table = 'tbl6'

